// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rescute.Infrastructure;

namespace rescute.Infrastructure.Migrations
{
    [DbContext(typeof(rescuteContext))]
    [Migration("20201120105601_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rescute")
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rescute.Domain.Aggregates.Animal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SamaritanId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SamaritanId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Samaritan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Samaritans");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.ReportLogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SamaritanId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("SamaritanId");

                    b.ToTable("ReportLogs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ReportLogItem");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.Commented", b =>
                {
                    b.HasBaseType("rescute.Domain.Entities.LogItems.ReportLogItem");

                    b.Property<string>("RepliesToId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("RepliesToId");

                    b.HasDiscriminator().HasValue("Commented");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.Contributed", b =>
                {
                    b.HasBaseType("rescute.Domain.Entities.LogItems.ReportLogItem");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("BillId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("BillId");

                    b.HasDiscriminator().HasValue("Contributed");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.DocumentedLogItem", b =>
                {
                    b.HasBaseType("rescute.Domain.Entities.LogItems.ReportLogItem");

                    b.HasDiscriminator().HasValue("DocumentedLogItem");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.TransportRequested", b =>
                {
                    b.HasBaseType("rescute.Domain.Entities.LogItems.ReportLogItem");

                    b.HasDiscriminator().HasValue("TransportRequested");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.BillAttached", b =>
                {
                    b.HasBaseType("rescute.Domain.Entities.LogItems.DocumentedLogItem");

                    b.Property<bool>("ContributionRequested")
                        .HasColumnType("bit");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("BillAttached");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.ReportCreated", b =>
                {
                    b.HasBaseType("rescute.Domain.Entities.LogItems.DocumentedLogItem");

                    b.HasDiscriminator().HasValue("ReportCreated");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Animal", b =>
                {
                    b.HasOne("rescute.Domain.Aggregates.Report", null)
                        .WithMany("Animals")
                        .HasForeignKey("ReportId");

                    b.OwnsOne("rescute.Domain.ValueObjects.AnimalType", "Type", b1 =>
                        {
                            b1.Property<string>("AnimalId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Report", b =>
                {
                    b.HasOne("rescute.Domain.Aggregates.Samaritan", "Samaritan")
                        .WithMany()
                        .HasForeignKey("SamaritanId");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Samaritan", b =>
                {
                    b.OwnsOne("rescute.Shared.MyName", "FirstName", b1 =>
                        {
                            b1.Property<string>("SamaritanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("MaxLength")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SamaritanId");

                            b1.ToTable("Samaritans");

                            b1.WithOwner()
                                .HasForeignKey("SamaritanId");
                        });

                    b.OwnsOne("rescute.Shared.MyName", "LastName", b1 =>
                        {
                            b1.Property<string>("SamaritanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("MaxLength")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SamaritanId");

                            b1.ToTable("Samaritans");

                            b1.WithOwner()
                                .HasForeignKey("SamaritanId");
                        });

                    b.OwnsOne("rescute.Shared.PhoneNumber", "Mobile", b1 =>
                        {
                            b1.Property<string>("SamaritanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("IsMobile")
                                .HasColumnType("bit");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SamaritanId");

                            b1.ToTable("Samaritans");

                            b1.WithOwner()
                                .HasForeignKey("SamaritanId");
                        });
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.ReportLogItem", b =>
                {
                    b.HasOne("rescute.Domain.Aggregates.Report", null)
                        .WithMany("Logs")
                        .HasForeignKey("ReportId");

                    b.HasOne("rescute.Domain.Aggregates.Samaritan", "Samaritan")
                        .WithMany()
                        .HasForeignKey("SamaritanId");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.Commented", b =>
                {
                    b.HasOne("rescute.Domain.Entities.LogItems.ReportLogItem", "RepliesTo")
                        .WithMany()
                        .HasForeignKey("RepliesToId");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.Contributed", b =>
                {
                    b.HasOne("rescute.Domain.Entities.LogItems.BillAttached", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId");
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.DocumentedLogItem", b =>
                {
                    b.OwnsMany("rescute.Domain.ValueObjects.Document", "Documents", b1 =>
                        {
                            b1.Property<string>("DocumentedLogItemId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Alias")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FileName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DocumentedLogItemId", "Id");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentedLogItemId");

                            b1.OwnsOne("rescute.Domain.ValueObjects.DocumentType", "Type", b2 =>
                                {
                                    b2.Property<string>("DocumentedLogItemId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<int>("DocumentId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("DocumentedLogItemId", "DocumentId");

                                    b2.ToTable("Documents");

                                    b2.WithOwner()
                                        .HasForeignKey("DocumentedLogItemId", "DocumentId");
                                });
                        });
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.TransportRequested", b =>
                {
                    b.OwnsOne("rescute.Domain.ValueObjects.MapPoint", "EventLocation", b1 =>
                        {
                            b1.Property<string>("TransportRequestedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("TransportRequestedId");

                            b1.ToTable("ReportLogs");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestedId");
                        });

                    b.OwnsOne("rescute.Domain.ValueObjects.MapPoint", "ToLocation", b1 =>
                        {
                            b1.Property<string>("TransportRequestedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("TransportRequestedId");

                            b1.ToTable("ReportLogs");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestedId");
                        });
                });

            modelBuilder.Entity("rescute.Domain.Entities.LogItems.ReportCreated", b =>
                {
                    b.OwnsOne("rescute.Domain.ValueObjects.MapPoint", "EventLocation", b1 =>
                        {
                            b1.Property<string>("ReportCreatedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("ReportCreatedId");

                            b1.ToTable("ReportLogs");

                            b1.WithOwner()
                                .HasForeignKey("ReportCreatedId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
