// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rescute.Infrastructure;

namespace rescute.Infrastructure.Migrations
{
    [DbContext(typeof(rescuteContext))]
    partial class rescuteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rescute")
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rescute.Domain.Aggregates.Animal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BirthCertificateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroducedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("IntroducedBy");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepliesTo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RepliesTo");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Samaritan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Samaritans");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.TimelineEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnimalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("AnimalId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("TimelineEvents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TimelineEvent");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.TimelineEventWithAttachments", b =>
                {
                    b.HasBaseType("rescute.Domain.Aggregates.TimelineEvents.TimelineEvent");

                    b.HasDiscriminator().HasValue("TimelineEventWithAttachments");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.TransportRequested", b =>
                {
                    b.HasBaseType("rescute.Domain.Aggregates.TimelineEvents.TimelineEvent");

                    b.HasDiscriminator().HasValue("TransportRequested");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.BillAttached", b =>
                {
                    b.HasBaseType("rescute.Domain.Aggregates.TimelineEvents.TimelineEventWithAttachments");

                    b.Property<bool>("ContributionRequested")
                        .HasColumnType("bit");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("BillAttached");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.StatusReported", b =>
                {
                    b.HasBaseType("rescute.Domain.Aggregates.TimelineEvents.TimelineEventWithAttachments");

                    b.HasDiscriminator().HasValue("StatusReported");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Animal", b =>
                {
                    b.HasOne("rescute.Domain.Aggregates.Samaritan", null)
                        .WithMany()
                        .HasForeignKey("IntroducedBy");

                    b.OwnsOne("rescute.Domain.ValueObjects.AnimalType", "Type", b1 =>
                        {
                            b1.Property<string>("AnimalId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsMany("rescute.Domain.ValueObjects.Attachment", "Attachments", b1 =>
                        {
                            b1.Property<string>("AnimalId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FileName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AnimalId", "Id");

                            b1.ToTable("AnimalAttachments");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");

                            b1.OwnsOne("rescute.Domain.ValueObjects.AttachmentType", "Type", b2 =>
                                {
                                    b2.Property<string>("AttachmentAnimalId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<int>("AttachmentId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AttachmentAnimalId", "AttachmentId");

                                    b2.ToTable("AnimalAttachments");

                                    b2.WithOwner()
                                        .HasForeignKey("AttachmentAnimalId", "AttachmentId");
                                });
                        });
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Comment", b =>
                {
                    b.HasOne("rescute.Domain.Aggregates.Samaritan", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("rescute.Domain.Aggregates.TimelineEvents.TimelineEvent", null)
                        .WithMany()
                        .HasForeignKey("RepliesTo");
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.Samaritan", b =>
                {
                    b.OwnsOne("rescute.Shared.Name", "FirstName", b1 =>
                        {
                            b1.Property<string>("SamaritanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("MaxLength")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SamaritanId");

                            b1.ToTable("Samaritans");

                            b1.WithOwner()
                                .HasForeignKey("SamaritanId");
                        });

                    b.OwnsOne("rescute.Shared.Name", "LastName", b1 =>
                        {
                            b1.Property<string>("SamaritanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("MaxLength")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SamaritanId");

                            b1.ToTable("Samaritans");

                            b1.WithOwner()
                                .HasForeignKey("SamaritanId");
                        });

                    b.OwnsOne("rescute.Shared.PhoneNumber", "Mobile", b1 =>
                        {
                            b1.Property<string>("SamaritanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("IsMobile")
                                .HasColumnType("bit");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SamaritanId");

                            b1.ToTable("Samaritans");

                            b1.WithOwner()
                                .HasForeignKey("SamaritanId");
                        });
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.TimelineEvent", b =>
                {
                    b.HasOne("rescute.Domain.Aggregates.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("rescute.Domain.Aggregates.Samaritan", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.TimelineEventWithAttachments", b =>
                {
                    b.OwnsMany("rescute.Domain.ValueObjects.Attachment", "Attachments", b1 =>
                        {
                            b1.Property<string>("TimelineEventWithAttachmentsId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FileName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TimelineEventWithAttachmentsId", "Id");

                            b1.ToTable("TimelineEventAttachments");

                            b1.WithOwner()
                                .HasForeignKey("TimelineEventWithAttachmentsId");

                            b1.OwnsOne("rescute.Domain.ValueObjects.AttachmentType", "Type", b2 =>
                                {
                                    b2.Property<string>("AttachmentTimelineEventWithAttachmentsId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<int>("AttachmentId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AttachmentTimelineEventWithAttachmentsId", "AttachmentId");

                                    b2.ToTable("TimelineEventAttachments");

                                    b2.WithOwner()
                                        .HasForeignKey("AttachmentTimelineEventWithAttachmentsId", "AttachmentId");
                                });
                        });
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.TransportRequested", b =>
                {
                    b.OwnsOne("rescute.Domain.ValueObjects.MapPoint", "EventLocation", b1 =>
                        {
                            b1.Property<string>("TransportRequestedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("TransportRequestedId");

                            b1.ToTable("TimelineEvents");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestedId");
                        });

                    b.OwnsOne("rescute.Domain.ValueObjects.MapPoint", "ToLocation", b1 =>
                        {
                            b1.Property<string>("TransportRequestedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("TransportRequestedId");

                            b1.ToTable("TimelineEvents");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestedId");
                        });
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.BillAttached", b =>
                {
                    b.OwnsMany("rescute.Domain.ValueObjects.BillContribution", "Contributions", b1 =>
                        {
                            b1.Property<string>("BillAttachedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint");

                            b1.Property<string>("ContributorId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TransactionId")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BillAttachedId", "Id");

                            b1.HasIndex("ContributorId");

                            b1.ToTable("BillContributions");

                            b1.WithOwner()
                                .HasForeignKey("BillAttachedId");

                            b1.HasOne("rescute.Domain.Aggregates.Samaritan", null)
                                .WithMany()
                                .HasForeignKey("ContributorId");
                        });
                });

            modelBuilder.Entity("rescute.Domain.Aggregates.TimelineEvents.StatusReported", b =>
                {
                    b.OwnsOne("rescute.Domain.ValueObjects.MapPoint", "EventLocation", b1 =>
                        {
                            b1.Property<string>("StatusReportedId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("StatusReportedId");

                            b1.ToTable("TimelineEvents");

                            b1.WithOwner()
                                .HasForeignKey("StatusReportedId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
